
set(RESOURCES "Resources")
set(RESOURCES_ASSETS "${RESOURCES}/Assets")
set(RESOURCES_ASSETS_TEXTURES "${RESOURCES_ASSETS}/Textures")
set(RESOURCES_CONFIGFILES "${RESOURCES}/Configfiles")

file(MAKE_DIRECTORY "${RESOURCES_ASSETS}/Fonts")
file(MAKE_DIRECTORY "${RESOURCES_ASSETS}/Shaders")
file(MAKE_DIRECTORY "${RESOURCES_ASSETS}/Sounds")
file(MAKE_DIRECTORY "${RESOURCES_ASSETS}/Textures")

file(MAKE_DIRECTORY "${RESOURCES_ASSETS_TEXTURES}/Misc")
file(MAKE_DIRECTORY "${RESOURCES_ASSETS_TEXTURES}/NPCs")
file(MAKE_DIRECTORY "${RESOURCES_ASSETS_TEXTURES}/Player")
file(MAKE_DIRECTORY "${RESOURCES_ASSETS_TEXTURES}/Tiles")

file(MAKE_DIRECTORY "${RESOURCES}/Databases")
file(MAKE_DIRECTORY "${RESOURCES}/Logs")
file(MAKE_DIRECTORY "${RESOURCES}/Savefiles")
file(MAKE_DIRECTORY "${RESOURCES_CONFIGFILES}/Assets")
file(MAKE_DIRECTORY "${RESOURCES_CONFIGFILES}/Uniform")
